name: katex
version: 0.1.0
author: Adam J. Cook <adam.joseph.cook@gmail.com>
description: Fast math typesetting for the web, ported to Dart.
homepage: https://github.com/adamjcook/katex.dart
dependencies:
  browser: any
  logging: '>=0.9.2 <0.10.0'
  quiver: '>=0.18.2 <0.19.0'
dev_dependencies:
  benchmark_harness: '>=1.0.4 <2.0.0'
  html5lib: '>=0.12.0 <0.13.0'
  less_transformer: '>=0.1.0 <0.2.0'
  path: '>=1.3.0 <2.0.0'
  unittest: 'any'
  yaml: '>=2.0.1+1 <3.0.0'
environment:
  sdk: '>=1.6.0'
transformers:
  - $dart2js:
      minify: true
      csp: true
  - less_transformer:
      src:
        - lib/static/katex.less