name: flutter_math_fork_example
description: A Flutter Package (Demo) to render LaTeX with pure Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork:
    path: ../
  flutter_tex: ^4.0.3+4
  google_fonts: ^2.3.2
  platform: ^3.1.0
  provider: ^6.0.2

dev_dependencies:
  extra_pedantic: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
